<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Logger" Id="{75e85e1a-2f6e-03ab-0c87-a271e0cb3059}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_explicit_call'} 
FUNCTION_BLOCK ABSTRACT FB_Logger IMPLEMENTS I_Logger
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	stSettings:		ST_LoggerSettings;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// https://peterzerlauth.com/]]></ST>
    </Implementation>
    <Method Name="M_Critical" Id="{2c8a5c1c-03ce-0010-0a47-0212c31c090a}">
      <Declaration><![CDATA[METHOD M_Critical
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Debug" Id="{e3912c08-cf4d-007c-00c3-1ee82a0d186f}">
      <Declaration><![CDATA[METHOD M_Debug
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Error" Id="{03bff8e4-5538-0253-230e-ccdcab79aad4}">
      <Declaration><![CDATA[METHOD M_Error
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Info" Id="{2ddc58e6-49ca-01d6-1dfd-87a9538cab59}">
      <Declaration><![CDATA[METHOD M_Info
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Log" Id="{4452c859-b6bf-01af-3dbe-b917edbc909d}">
      <Declaration><![CDATA[METHOD M_Log
VAR_INPUT
	LogLevel:		E_LogLevel;
	Message:		STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Warning" Id="{0990c154-baa1-08fc-1e9d-e8bdc2ce38cc}">
      <Declaration><![CDATA[METHOD M_Warning
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="P_Settings" Id="{5e4581b5-fd00-038d-0acd-5f616a88193b}">
      <Declaration><![CDATA[{attribute 'suppress_wrn_C0410'}
PROPERTY PUBLIC P_Settings : reference to ST_LoggerSettings]]></Declaration>
      <Get Name="Get" Id="{f971d380-5501-072f-309e-ea23dbbab652}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_Settings ref= stSettings;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{d8f12c65-db54-0766-3ded-457a5d3a2ae7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_Settings ref= stSettings;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>