<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_TcLogger" Id="{ac5cb775-ca52-0255-1111-53dd9dd30a39}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TcLogger EXTENDS FB_Logger
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// https://peterzerlauth.com/]]></ST>
    </Implementation>
    <Method Name="M_Critical" Id="{2982efed-966c-01d1-1cd8-85c5858fe88f}">
      <Declaration><![CDATA[METHOD M_Critical
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_Log(E_LogLevel.Critical, Message);]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Debug" Id="{e9b66a72-8740-048e-056d-384013e2c854}">
      <Declaration><![CDATA[METHOD M_Debug
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_Log(E_LogLevel.Debug, Message);]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Error" Id="{f2d5f7b6-19e2-0369-0afb-2b4249522bc0}">
      <Declaration><![CDATA[METHOD M_Error
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_Log(E_LogLevel.Error, Message);]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Info" Id="{4effdfa3-d848-028b-038f-a8a5dc542fba}">
      <Declaration><![CDATA[METHOD M_Info
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_Log(E_LogLevel.Info, Message);]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Log" Id="{a246f3a7-4c6c-0276-17fe-454760b02efa}">
      <Declaration><![CDATA[METHOD M_Log
VAR_INPUT
	LogLevel:		E_LogLevel;
	Message:		STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[CASE LogLevel OF
	E_LogLevel.Debug:
		IF LogLevel >= stSettings.eLogLevelMinimum AND LogLevel <= stSettings.eLogLevelMaximum THEN
			ADSLOGSTR(ADSLOG_MSGTYPE_STRING OR ADSLOG_MSGTYPE_LOG,'Debug: %s', Message);
		END_IF
		
	E_LogLevel.Info:
		IF LogLevel >= stSettings.eLogLevelMinimum AND LogLevel <= stSettings.eLogLevelMaximum THEN
			ADSLOGSTR(ADSLOG_MSGTYPE_HINT OR ADSLOG_MSGTYPE_LOG,'Info: %s', Message);
		END_IF
		
	E_LogLevel.Warning:
		IF LogLevel >= stSettings.eLogLevelMinimum AND LogLevel <= stSettings.eLogLevelMaximum THEN
			ADSLOGSTR(ADSLOG_MSGTYPE_WARN OR ADSLOG_MSGTYPE_LOG,'Warning: %s', Message);
		END_IF
		
	E_LogLevel.Error:
		IF LogLevel >= stSettings.eLogLevelMinimum AND LogLevel <= stSettings.eLogLevelMaximum THEN
			ADSLOGSTR(ADSLOG_MSGTYPE_ERROR OR ADSLOG_MSGTYPE_LOG,'Error: %s', Message);
		END_IF
		
	E_LogLevel.Critical:
		IF LogLevel >= stSettings.eLogLevelMinimum AND LogLevel <= stSettings.eLogLevelMaximum THEN
			ADSLOGSTR(ADSLOG_MSGTYPE_ERROR OR ADSLOG_MSGTYPE_LOG,'Critical: %s', Message);
		END_IF
		
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Warning" Id="{95cba8b4-3106-0b72-0c22-17a6383ccea8}">
      <Declaration><![CDATA[METHOD M_Warning
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_Log(E_LogLevel.Warning, Message);]]></ST>
      </Implementation>
    </Method>
    <Property Name="P_Settings" Id="{01dd4810-8f37-0c4a-3c92-76d701892bf0}">
      <Declaration><![CDATA[{attribute 'suppress_wrn_C0410'}
PROPERTY PUBLIC P_Settings : reference to ST_LoggerSettings]]></Declaration>
      <Get Name="Get" Id="{bf3b7823-3d52-086a-3df0-38d0383f978b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_Settings ref= stSettings;]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{9c539151-e1cf-0117-1143-0dee1b6c393c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[P_Settings ref= stSettings;]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>