<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Target" Id="{03a9cd9d-3845-0fb8-3250-b0e6042a4dfc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Target
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Target">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>