<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Logger" Id="{75e85e1a-2f6e-03ab-0c87-a271e0cb3059}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_Logger IMPLEMENTS I_Logger
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	stParameter:		ST_Logger;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Critical" Id="{2c8a5c1c-03ce-0010-0a47-0212c31c090a}">
      <Declaration><![CDATA[METHOD M_Critical
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Debug" Id="{e3912c08-cf4d-007c-00c3-1ee82a0d186f}">
      <Declaration><![CDATA[METHOD M_Debug
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Error" Id="{03bff8e4-5538-0253-230e-ccdcab79aad4}">
      <Declaration><![CDATA[METHOD M_Error
VAR_INPUT
	Message:		STRING(255);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Info" Id="{2ddc58e6-49ca-01d6-1dfd-87a9538cab59}">
      <Declaration><![CDATA[METHOD M_Info
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Log" Id="{4452c859-b6bf-01af-3dbe-b917edbc909d}">
      <Declaration><![CDATA[METHOD M_Log
VAR_INPUT
	LogLevel:		E_LogLevel;
	Message:		STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Warning" Id="{0990c154-baa1-08fc-1e9d-e8bdc2ce38cc}">
      <Declaration><![CDATA[METHOD M_Warning
VAR_INPUT
	Message	: STRING(255);
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="P_Parameter" Id="{c3786a2f-91e3-0ec1-3f7a-a85190472496}">
      <Declaration><![CDATA[PROPERTY PUBLIC P_Parameter : reference to ST_Logger]]></Declaration>
      <Get Name="Get" Id="{5db43e1f-632d-0054-2947-dbccd362cd17}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Logger">
      <LineId Id="16" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.M_Critical">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.M_Debug">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.M_Error">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.M_Info">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.M_Log">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.M_Warning">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Logger.P_Parameter.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>